name: PR_unit_tests

on:
  pull_request:
    branches:
      - 'GithubActionsDemonstration'
  push:
    branches:
      - 'Testing'

jobs:
  Unit-test:
    name: Run unit tests on PR in GithubActionsDemonstration
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'
      - name: Run unit tests
        run: cd ./NewsApplication; chmod +x gradlew; ./gradlew test
        
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86
          profile: Pixel 4
          script: ./gradlew connectedCheck --stacktrace
        
    
